### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by DSpeichert** [SerwerSMSpl/serwersms-php-api-v2#1]
```
[2015-01-18 10:23:42] local.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/ubuntu/vendor/serwersms/serwersms-php-client/src/SerwerSMS.php:100
```

**Comment by SerwerSMSpl** [comment]
What action are you doing? What are the parameters?

**Comment by DSpeichert** [comment]
Wygląda na to, że problem występuje gdy wysyłka wiadomości jest zablokowana dla konta (pakiet pre-paid stracił ważność).

**Comment by SerwerSMSpl** [comment]
Niestety nie udało nam się osiągnąć takiego efektu. W przypadku blokady wysyłki zwracany jest poprawny komunikat: Wysyłanie wiadomości SMS zostało zablokowane. Być może jest to kwestia innych ustawień na koncie. Prosimy o podesłanie loginu w celu weryfikacji pozostałych parametrów. Może być mailowo na adres jarek@serwersms.pl lub proszę o zgłoszenie poprzez helpdesk po zalogowaniu się do Panelu Klienta.
