### ISSUE TITLE
Błędy w opisie metody

### ISSUE THREAD

**Issue by wiiiteek** [SerwerSMSpl/serwersms-php-api-v2#6]
Klasa `Messages` - metody mają opisane, że zwracają `array` kiedy tak naprawdę zwracają obiekt. Dobrze by było to poprawić, bo się na tym naciąłem dzisiaj w jednym projekcie ;)

Ew. można  w głównej klasie zamienić `json_decode($answer);` na `json_decode($answer, true);` w metodzie `call()`, tak aby zwrócona została tablica i wtedy opis pozostaje dobry

**Comment by SerwerSMSpl** [comment]
Dzień dobry,

dziękujemy za informację. Opisy zostały poprawione.
