### ISSUE TITLE
Semantic versioning broken

### ISSUE THREAD

**Issue by marcinlawnik** [SerwerSMSpl/serwersms-php-api-v2#8]
Hi,

I just nearly broke a system in production because of you failing to follow semantic versioning.

(https://semver.org/ and https://getcomposer.org/doc/articles/versions.md) <= recommended reading

**Changing the way the library is initialized IS A MAJOR BREAKING CHANGE.**

What is now released as 1.1.0 should be 2.0.0

**I request that you remove release 1.1.0 from GitHub and Packagist and release it as 2.0.0**

Please fix ASAP

**Comment by marcinlawnik** [comment]
Aforementioned change:
https://github.com/SerwerSMSpl/serwersms-php-api-v2/commit/8645f426d4c106df3ddcc4d20c304bd88b412923

**Comment by SerwerSMSpl** [comment]
I apologize for the late reply. Release was fixed.
